version: 0.2

# AWS CodeBuild Build Specification for Victoria Fisheries Bot
# This file defines the build process for the WhatsApp ordering bot

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - echo "Node version:" $(node --version)
      - echo "NPM version:" $(npm --version)
      - npm ci
  
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - echo "Current directory:" $(pwd)
      - echo "Listing files..."
      - ls -la
      
      # Run tests
      - echo "Running tests..."
      - npm test || echo "Warning - Tests failed but continuing build"
      
      # Run linter if available
      - echo "Running linter..."
      - npm run lint 2>/dev/null || echo "No lint script found, skipping..."
      
      # Check for security vulnerabilities
      - echo "Checking for security vulnerabilities..."
      - npm audit --audit-level=high || echo "Security check complete with warnings"
  
  build:
    commands:
      - echo "Building application..."
      - echo "Build started at" $(date)
      
      # Create deployment directory
      - echo "Creating deployment package..."
      - mkdir -p deployment
      
      # Copy application files (excluding development files and artifacts)
      - echo "Copying application files..."
      - rsync -av --progress \
          --exclude 'node_modules' \
          --exclude 'deployment' \
          --exclude '.git' \
          --exclude '.env' \
          --exclude '*.log' \
          --exclude 'terraform' \
          --exclude 'coverage' \
          --exclude '.nyc_output' \
          ./ deployment/
      
      # Install production dependencies in deployment directory
      - echo "Installing production dependencies..."
      - cd deployment
      - npm ci --production --ignore-scripts
      
      # Verify critical files exist
      - echo "Verifying deployment package..."
      - test -f package.json || (echo "ERROR - package.json missing" && exit 1)
      - test -f server.js || (echo "ERROR - server.js missing" && exit 1)
      - test -f appspec.yml || (echo "ERROR - appspec.yml missing" && exit 1)
      - test -d scripts || (echo "ERROR - scripts directory missing" && exit 1)
      
      # Display package contents
      - echo "Deployment package contents:"
      - find . -type f | head -20
      
      - cd ..
  
  post_build:
    commands:
      - echo "Post-build phase..."
      - echo "Build completed at" $(date)
      
      # Create build info file
      - echo "Creating build metadata..."
      - cat > deployment/build-info.json << EOF
        {
          "buildId": "$CODEBUILD_BUILD_ID",
          "buildNumber": "$CODEBUILD_BUILD_NUMBER",
          "sourceVersion": "$CODEBUILD_RESOLVED_SOURCE_VERSION",
          "buildTime": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "region": "$AWS_REGION"
        }
        EOF
      
      # Display build summary
      - echo "========================================="
      - echo "Build Summary"
      - echo "========================================="
      - echo "Build ID: $CODEBUILD_BUILD_ID"
      - echo "Source Version: $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "Build completed successfully!"
      - echo "========================================="

artifacts:
  files:
    - '**/*'
  base-directory: deployment
  discard-paths: no
  name: victoria-bot-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - 'node_modules/**/*'

reports:
  test-results:
    files:
      - 'test-results/**/*'
    file-format: 'JUNITXML'
    base-directory: deployment
